### PR TITLE
Blog controllers

### PR DESCRIPTION
**Pull request by GOlivierNation**
What is Done on this PR:

    For each URL you should create:
        A route.
        An action in the correct controller.
        A view file.

    View files should include only placeholders written in plain HTML, e.g:
        Here is a list of posts for a given user

    Make sure that you added code to handle only the 4 required URLs.

### CODE REVIEW

**Review by medaminedev66 — CHANGES_REQUESTED** [review]
Hi @GOlivierNation, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linters errors, please fix those errors and request another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by GOlivierNation** [comment]
Thanks @medaminedev66 but I've cancelled the submission before.

**Comment by medaminedev66** [comment]
> Thanks @medaminedev66 but I've cancelled the submission before.

It's ok, @GOlivierNation. Invalid Code Review Request does not count into the code reviews limit. Take your time with solving linters errors, and request another review.

**Review by Whoistolu — APPROVED** [review]
### Hi @GOlivierNation 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [OPTIONAL] Kindly ensure that `node_modules` is ignored by `gitignore`. This will make your work more professional.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
